CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE
ON Customers
FOR EACH ROW
BEGIN

    :NEW.LastModified := SYSDATE;

END;
/
CREATE TABLE AuditLog (

    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    TransactionID NUMBER,

    AccountID NUMBER,

    TransactionDate DATE,

    Amount NUMBER,

    TransactionType VARCHAR2(20),

    LogDate DATE
);
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN

    INSERT INTO AuditLog(

        TransactionID,
        AccountID,
        TransactionDate,
        Amount,
        TransactionType,
        LogDate

    )
    VALUES(

        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.TransactionDate,
        :NEW.Amount,
        :NEW.TransactionType,
        SYSDATE

    );

END;
/
CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT
ON Transactions
FOR EACH ROW

DECLARE
    v_balance NUMBER;

BEGIN

    IF :NEW.TransactionType = 'Deposit' THEN

        IF :NEW.Amount <= 0 THEN

            RAISE_APPLICATION_ERROR(
                -20001,
                'Deposit amount must be positive'
            );

        END IF;

    ELSIF :NEW.TransactionType = 'Withdrawal' THEN

        SELECT Balance
        INTO v_balance
        FROM Accounts
        WHERE AccountID = :NEW.AccountID;

        IF :NEW.Amount > v_balance THEN

            RAISE_APPLICATION_ERROR(
                -20002,
                'Insufficient account balance'
            );

        END IF;

    END IF;

END;
/
UPDATE Customers
SET Balance = 5000
WHERE CustomerID = 1;
INSERT INTO Transactions(
    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType
)
VALUES(
    10,
    1,
    SYSDATE,
    500,
    'Deposit'
);
SELECT * FROM AuditLog;
INSERT INTO Transactions(
    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType
)
VALUES(
    11,
    1,
    SYSDATE,
    -100,
    'Deposit'
);